function x_axis(n, axis_start, axis_end)%ÀıÈç£¬n = 400, axis_start = 0,axis_end = 100

set(gca, 'xaxislocation', 'top', 'xlim', [1 n], 'xtick', 1 : ((n - 1) / 10) : n,...
    'xtickLabel',{num2str(axis_start),...
    num2str(axis_start + (axis_end - axis_start)/10), ...
    num2str(axis_start + 2 * (axis_end - axis_start)/10), ...
    num2str(axis_start + 3 * (axis_end - axis_start)/10), ...
    num2str(axis_start + 4 * (axis_end - axis_start)/10), ...
    num2str(axis_start + 5 * (axis_end - axis_start)/10), ...
    num2str(axis_start + 6 * (axis_end - axis_start)/10), ...
    num2str(axis_start + 7 * (axis_end - axis_start)/10), ...
    num2str(axis_start + 8 * (axis_end - axis_start)/10), ...
    num2str(axis_start + 9 * (axis_end - axis_start)/10), ...
    num2str(axis_start + (axis_end - axis_start))})